# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWtNRibw798IrTCCBS02SU-4fc42ju2W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

df = pd.read_csv("retail_sales_data.csv")
df.head()

df.info()
df.describe()

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Month"] = df["Order Date"].dt.to_period("M")

monthly_sales = df.groupby("Month")["Sales"].sum().reset_index()
monthly_sales["Month"] = monthly_sales["Month"].astype(str)

sns.lineplot(data=monthly_sales, x="Month", y="Sales", marker="o", color="green")
plt.title("Monthly Sales Trend")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

category_profit = df.groupby("Category")["Profit"].sum().reset_index()

sns.barplot(data=category_profit, x="Category", y="Profit", palette="viridis")
plt.title("Total Profit by Category")
plt.show()

sns.scatterplot(data=df, x="Discount", y="Profit", hue="Category", alpha=0.7)
plt.title("Discount vs Profit")
plt.show()

region_sales = df.groupby("Region")["Sales"].sum().reset_index()

sns.barplot(data=region_sales, x="Region", y="Sales", palette="mako")
plt.title("Sales by Region")
plt.show()

## Key Insights:
- Sales peaked in months [you will observe this visually]
- [Category] earned the highest profit
- Deep discounts often reduce profitability
- [Region] contributed most to total sales